#!/usr/bin/env python
# -*- coding: utf-8 -*-
#####################################################################
#  Laudeci Oliveira <laudeci@ubuntu.com>
#  Ursula Junque <ursinha@ubuntu.com>
#
#  Copyright 2011 unity-launcher-editor-dev.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; version 3 only.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#####################################################################
import sys
import os

BASE_PATH=os.path.dirname(os.path.abspath(sys.argv[0]))
sys.path.append(os.path.dirname(BASE_PATH +'/'))

from gi.repository import Gio
from unitylaunchereditor.dialogs.app import MainWindow

try:
    import gtk
except:
    print "You need to install pyGTK or GTKv2 ",
    print "or set your PYTHONPATH correctly."
    print "try: export PYTHONPATH=",
    print "/usr/local/lib/python2.X/site-packages/"
    sys.exit(1)

def main():
    app = MainWindow(Gio.Settings('com.canonical.Unity.Launcher'))
    app.show_all()
    gtk.main()

if __name__ == "__main__":
    main()
